### ISSUE TITLE
Path reservation issues

### ISSUE THREAD

**Issue by tuxbear** [Urigo/angular2-meteor#155]
Hi!

After installing meteor-angular2 i get path reservation issues all over the place.

If I delete the file mentioned, the error simply returns for a different path after maybe one successful launch of meteor.

Any idea what might be the cause of these? I see from googling that bower has been named culprit earlier, but I'm not using bower.
                                              
/Users/tuxbear/.meteor/packages/meteor-tool/.1.1.10.f30p2m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:245
                                                throw(ex);
                                                      ^
Error: Path reservation conflict: app/client/stylesheets/semantic-ui/definitions/behaviors/api.js
    at Builder.reserve (/tools/isobuild/builder.js:297:15)
    at /tools/isobuild/bundler.js:1111:15
    at /tools/isobuild/bundler.js:1103:11
    at Array.forEach (native)
    at /tools/isobuild/bundler.js:1102:20
    at Array.forEach (native)
    at ClientTarget.<anonymous> (/tools/isobuild/bundler.js:1101:30)
    at ClientTarget.write (/tools/isobuild/bundler.js:1110:5)
    at /tools/isobuild/bundler.js:1847:30
    at Object.keys.forEach.subBuilder (/tools/isobuild/bundler.js:1971:9)
    at Array.forEach (native)
    at /tools/isobuild/bundler.js:1963:26
    at /tools/isobuild/bundler.js:2010:7
    at /tools/isobuild/bundler.js:2287:22
    at /tools/utils/buildmessage.js:268:13
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:261:29
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:259:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:250:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at Object.capture (/tools/utils/buildmessage.js:249:19)
    at Object.exports.bundle (/tools/isobuild/bundler.js:2128:31)
    at /tools/runners/run-app.js:551:36
    at time (/tools/tool-env/profile.js:232:28)
    at Function.run (/tools/tool-env/profile.js:377:12)
    at bundleApp (/tools/runners/run-app.js:541:34)
    at [object Object]._.extend._runOnce (/tools/runners/run-app.js:594:35)
    at [object Object]._.extend._fiber (/tools/runners/run-app.js:858:28)
    at /tools/runners/run-app.js:396:12

**Comment by btnbrl** [comment]
I had the same issue also, as I'm also starting with meteor-angular. What I did is to delete all *.js files generated by *.ts and relaunch meteor. That usually works. You can delete the api.js only if you like. It also works.

**Comment by tuxbear** [comment]
Yes I noticed this works but the problem comes back after some live editing or a restart of meteor :(

**Comment by btnbrl** [comment]
Yes, that is a problem I have too.

**Comment by barbatus** [comment]
If you are using WebStorm or Atom, add `tsconfig.json` to your app with the content as follows:
```
{
  "compileOnSave": false,
  "buildOnSave": false
}
```
This will stop compiling ts-files in the IDE and, thus, generating js-files.

For other information or if you have questions, read Angular2-Tutorial first.

**Comment by tuxbear** [comment]
Yes, this was the issue, thank you! I want the IDE to compile the files so I can see mistakes as I make them, so I have configures the IDE to just dump the generated files outside the meteor project
