### ISSUE TITLE
Fix Angular2-Meteor NPM for Windows

### ISSUE THREAD

**Issue by barbatus** [Urigo/angular2-meteor#185]
Original source of the issue is here:
https://github.com/Urigo/angular2-meteor/issues/171#issuecomment-199806027

**Comment by Devidian** [comment]
any workaround until this is fixed ?

**Comment by barbatus** [comment]
https://cygwin.com might help.

**Comment by barbatus** [comment]
Ok, I added some temporary fix. Please, check that it works for you.

**Comment by Devidian** [comment]
```
npm install https://github.com/Urigo/angular2-meteor --save

> angular2-meteor@0.5.0-beta.1 install ..\GIT\Meteor\webapp\node_modules\angular2-meteor
> node install.js

module.js:327
    throw err;
    ^

Error: Cannot find module 'fs.extra'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (..\GIT\Meteor\webapp\node_modules\angular2-meteor\install.js:1:72)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
mamiwelt-meteor-npm@0.0.1 ..\GIT\Meteor\webapp
`-- es6-shim@0.35.0

npm WARN angular2-meteor@0.5.0-beta.1 requires a peer of angular2@2.0.0-beta.9 but none was installed.
npm WARN angular2-meteor@0.5.0-beta.1 requires a peer of es6-shim@^0.33.3 but none was installed.
npm WARN angular2-meteor@0.5.0-beta.1 requires a peer of zone.js@0.5.15 but none was installed.
npm WARN mamiwelt-meteor-npm@0.0.1 No repository field.
npm WARN mamiwelt-meteor-npm@0.0.1 No license field.
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Maik Laschober\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "https://github.com/Urigo/angular2-meteor" "--save"
npm ERR! node v4.3.1
npm ERR! npm  v3.8.2
npm ERR! code ELIFECYCLE

npm ERR! angular2-meteor@0.5.0-beta.1 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-meteor@0.5.0-beta.1 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-meteor package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-meteor
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-meteor
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     ..\GIT\Meteor\webapp\npm-debug.log
```

**Comment by Devidian** [comment]
`mv `on windows is typically `move `command

**Comment by barbatus** [comment]
Ok, there was some minor correction you might have missed. What would be if you try once more?

**Comment by Devidian** [comment]
seems to work now 

```
+-- angular2-meteor@0.5.0-beta.1  (git+https://github.com/Urigo/angular2-meteor.git#c29821a8256532df18f235c55e8127a16da6ea1f)
| +-- ejson@2.1.2
| | `-- underscore@1.8.3
| `-- fs.extra@1.3.2
|   +-- fs-extra@0.6.4
|   | +-- jsonfile@1.0.1
|   | +-- ncp@0.4.2
|   | `-- rimraf@2.2.8
|   +-- mkdirp@0.3.5
|   `-- walk@2.3.9
|     `-- foreachasync@3.0.0
```

**Comment by Devidian** [comment]
not working on the bootstrap npm

**Comment by barbatus** [comment]
what does it mean the bootstrap npm? does `npm install` work now?

**Comment by Devidian** [comment]
pardon,
 i meant:

```
npm install https://github.com/Urigo/angular2-meteor --save // this works fine
npm install https://github.com/Urigo/angular2-meteor-auto-bootstrap --save // this didn't work (mv still as issue)
```
i'am at home now will try it again tomorrow morning.

**Comment by tehaaron** [comment]
I am having this same issue with `mv` command on Windows for the `angular2-meteor-auto-bootstrap` package. Is there a solution without using cygwin before tomorrow?

**Comment by Devidian** [comment]
Being at work again, `npm install https://github.com/Urigo/angular2-meteor-auto-bootstrap --save` still not working on windows

**Comment by barbatus** [comment]
Ok, I committed fix (https://github.com/Urigo/angular2-meteor-auto-bootstrap/issues/4), will be available soon. Closing this one.

**Comment by Urigo** [comment]
@Devidian can you confirm it works for you?

**Comment by Devidian** [comment]
Currently on easter vacation. Checking on tuesday

**Comment by Devidian** [comment]
its working fine ;)
