### ISSUE TITLE
error running tests with angular2-runtime installed

### ISSUE THREAD

**Issue by denodaeus** [Urigo/angular2-meteor#251]
Including barbatus:angular2-runtime in the project is supposed to prevent the need for having to include zone.js and shims (reflect-metadata), but if I try running tests with a test runner, this doesn't seem to work:

```
meteor test --driver-package practicalmeteor:mocha
```

```
imports/ui/activity/work-item-menu/work-item-modal.component.ts (321, 5): Supplied parameters do not match any signature of call target.
W20160428-16:01:07.152(-4)? (STDERR)
W20160428-16:01:07.152(-4)? (STDERR) /Users/bsmith/.meteor/packages/meteor-tool/.1.3.2_4.krzmzr++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:267
W20160428-16:01:07.152(-4)? (STDERR)            				throw(ex);
W20160428-16:01:07.152(-4)? (STDERR)            				      ^
W20160428-16:01:07.155(-4)? (STDERR) ReferenceError: Zone is not defined
W20160428-16:01:07.155(-4)? (STDERR)     at Object.<anonymous> (/Users/bsmith/Development/git/qasymphony/kitsune-ui/node_modules/angular2/src/testing/fake_async.js:4:34)
W20160428-16:01:07.155(-4)? (STDERR)     at Module._compile (module.js:456:26)
W20160428-16:01:07.155(-4)? (STDERR)     at Object.Module._extensions..js (module.js:474:10)
W20160428-16:01:07.156(-4)? (STDERR)     at Module.load (module.js:356:32)
W20160428-16:01:07.156(-4)? (STDERR)     at Function.Module._load (module.js:312:12)
W20160428-16:01:07.156(-4)? (STDERR)     at Module.require (module.js:364:17)
W20160428-16:01:07.156(-4)? (STDERR)     at require (module.js:380:17)
W20160428-16:01:07.156(-4)? (STDERR)     at Object.<anonymous> (/Users/bsmith/Development/git/qasymphony/kitsune-ui/node_modules/angular2/src/testing/test_component_builder.js:20:20)
W20160428-16:01:07.156(-4)? (STDERR)     at Module._compile (module.js:456:26)
W20160428-16:01:07.156(-4)? (STDERR)     at Object.Module._extensions..js (module.js:474:10)
=> Exited with code: 8
imports/ui/activity/work-item-menu/work-item-modal.component.ts (321, 5): Supplied parameters do not match any signature of call target.
```

Note, this will work if I eagerly load all of my client code (placing it in /client), but not if I refer to the code lazily by importing it from the imports/ directory.

**Comment by denodaeus** [comment]
Seems like typings install es6-shim did the trick here for me.
