### ISSUE TITLE
`ReferenceError: Match is not defined` when using `meteor-client-side`

### ISSUE THREAD

**Issue by DAB0mB** [Urigo/angular2-meteor#331]
When using `meteor-client-side` (not `meteor`'s cli) I'm receiving the following error:

    `ReferenceError: check/esjon is not defined`

It seems to be caused by `angular2-meteor` which is relying on packages like `check` and `ejson` to be exposed, but apparently it ain't so good to rely on that.

The issue occurs since the following commit:

https://github.com/Urigo/angular2-meteor/commit/f05a40b3251cd72f84c23a260174f9bff97faa2f

To fix it, I use the following work around:
```js
import checkPack from 'meteor/check';
import ejsonPack from 'meteor/ejson';

Object.assign(window,
  checkPack,
  ejsonPack
);
```

Reverting this commit might solve this issue...

**Comment by barbatus** [comment]
Removing meteor namespaces were necessary since they are not available on the server.
But I'll look in a way to use it as `Package.ejson` and `Package.check`

**Comment by DAB0mB** [comment]
Unfortunately this problem is partially fixed, as for now I'm receiving the following error:

```
EXCEPTION: Error: Uncaught (in promise): EXCEPTION: Error in :0:0
ORIGINAL EXCEPTION: ReferenceError: Match is not defined
ORIGINAL STACKTRACE:
ReferenceError: Match is not defined
    at Function.DataObserver.pushCb (http://localhost:8100/build/js/app.bundle.js:93391:35)
    at ChatsPage.MeteorComponent._prepArgs (http://localhost:8100/build/js/app.bundle.js:93361:67)
    at ChatsPage.MeteorComponent.subscribe (http://localhost:8100/build/js/app.bundle.js:93298:24)
    at new ChatsPage (http://localhost:8100/build/js/app.bundle.js:118976:15)
    at DebugAppView._View_ChatsPage_Host0.createInternal (ChatsPage_Host.template.js:15:25)
    at DebugAppView.AppView.create (http://localhost:8100/build/js/app.bundle.js:15000:22)
    at DebugAppView.create (http://localhost:8100/build/js/app.bundle.js:15212:45)
    at ComponentFactory.create (http://localhost:8100/build/js/app.bundle.js:9882:37)
    at http://localhost:8100/build/js/app.bundle.js:58194:50
    at http://localhost:8100/build/js/app.bundle.js:98:195
ERROR CONTEXT:
[object Object]
```

Can you please re-open the issue?

**Comment by Urigo** [comment]
@DAB0mB update the title of the issue
