### ISSUE TITLE
Custom Type Declaration File - ReferenceError: Party is not defined

### ISSUE THREAD

**Issue by nebiljabari** [Urigo/angular2-meteor#339]
At step 7 of the tutorial when I add the <Party> type to the Mongo Collection object it breaks
`export let Parties = new Mongo.Collection<Party>('parties');`

```
Warning: creating anonymous collection. It will not be saved or synchronized over the network. (Pass null for the collection name to turn off this warning.)
~/.meteor/packages/meteor-tool/.1.3.4_3.ac04sf++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
throw(ex);
ReferenceError: Party is not defined
```

I've try different tricks (export/import interface, referencing the path) no success

**Comment by barbatus** [comment]
Make sure you have [party.d.ts](https://github.com/Urigo/meteor-angular2.0-socially/blob/master/typings/party.d.ts) in the typings folder

**Comment by nebiljabari** [comment]
Yes @barbatus it's in the right place
![ng](https://cloud.githubusercontent.com/assets/16270454/16985429/950d5c04-4e80-11e6-88bb-b1634170c0b4.png)

**Comment by barbatus** [comment]
Run meteor with TYPESCRIPT_LOG=2 and put the log here.

**Comment by nebiljabari** [comment]
very well @barbatus, here is the full log :

```
[[[[[ ~/socially ]]]]]                        

=> Started proxy.                             
=> Started MongoDB.                           
=> Meteor 1.3.5.1 is available. Update this project with 'meteor update'.
process files: client/imports/parties-form/parties-form.ts,client/imports/parties-list/parties-list.ts,client/imports/party-details/party-details.ts,typings/globals/es6-shim/index.d.ts,typings/globals/meteor/index.d.ts,typings/modules/es6-promise/index.d.ts,client/app.compo.ts,client/router.ts,typings/index.d.ts,typings/party.d.ts,client/main.ts
[meteor-typescript]: new build
[meteor-typescript]: emit file client/imports/parties-form/parties-form.ts
[meteor-typescript]: file client/imports/parties-form/parties-form.ts result is in cache
[meteor-typescript]: diagnostics re-evaluation: client/imports/parties-form/parties-form.ts
client/imports/parties-form/parties-form.ts (8, 28): Cannot find module './parties-form.html'.
client/imports/parties-form/parties-form.ts (9, 28): Cannot find module '/collections/parties'.
client/imports/parties-form/parties-form.ts (42, 46): Property 'updateValue' does not exist on type 'AbstractControl'.
[meteor-typescript]: emit file client/imports/parties-list/parties-list.ts
[meteor-typescript]: file client/imports/parties-list/parties-list.ts result is in cache
[meteor-typescript]: diagnostics re-evaluation: client/imports/parties-list/parties-list.ts
client/imports/parties-list/parties-list.ts (7, 36): Cannot find module '../../../collections/parties'.
client/imports/parties-list/parties-list.ts (10, 36): Cannot find module './parties-list.html'.
[meteor-typescript]: emit file client/imports/party-details/party-details.ts
[meteor-typescript]: file client/imports/party-details/party-details.ts result is in cache
[meteor-typescript]: diagnostics re-evaluation: client/imports/party-details/party-details.ts
client/imports/party-details/party-details.ts (6, 32): Cannot find module '../../../collections/parties'.
client/imports/party-details/party-details.ts (7, 32): Cannot find module './party-details.html'.
[meteor-typescript]: emit file client/app.compo.ts
[meteor-typescript]: file client/app.compo.ts result is in cache
[meteor-typescript]: diagnostics re-evaluation: client/app.compo.ts
client/app.compo.ts (5, 30): Cannot find module './app.compo.html'.
[meteor-typescript]: emit file client/router.ts
[meteor-typescript]: file client/router.ts result is in cache
[meteor-typescript]: file from cached: client/router.ts
[meteor-typescript]: emit file client/main.ts
[meteor-typescript]: file client/main.ts result is in cache
[meteor-typescript]: file from cached: client/main.ts
process files: typings/globals/es6-shim/index.d.ts,typings/globals/meteor/index.d.ts,typings/modules/es6-promise/index.d.ts,server/parties.ts,typings/index.d.ts,typings/party.d.ts
[meteor-typescript]: new build
[meteor-typescript]: emit file server/parties.ts
[meteor-typescript]: file server/parties.ts result is in cache
[meteor-typescript]: diagnostics re-evaluation: server/parties.ts
server/parties.ts (2, 26): Cannot find module '../collections/parties'.
I20160720-18:43:05.557(2)? Warning: creating anonymous collection. It will not be saved or synchronized over the network. (Pass null for the collection name to turn off this warning.)
W20160720-18:43:06.056(2)? (STDERR)           
W20160720-18:43:06.059(2)? (STDERR) /Users/JaNe/.meteor/packages/meteor-tool/.1.3.4_3.ac04sf++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20160720-18:43:06.061(2)? (STDERR)             				throw(ex);
W20160720-18:43:06.062(2)? (STDERR)             				      ^
W20160720-18:43:06.063(2)? (STDERR) ReferenceError: Party is not defined
W20160720-18:43:06.064(2)? (STDERR)     at meteorInstall.collections.parties.js (collections/parties.js:4:34)
W20160720-18:43:06.066(2)? (STDERR)     at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:153:1)
W20160720-18:43:06.068(2)? (STDERR)     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:82:1)
W20160720-18:43:06.069(2)? (STDERR)     at /Users/JaNe/socially/.meteor/local/build/programs/server/app/app.js:95:1
W20160720-18:43:06.071(2)? (STDERR)     at /Users/JaNe/socially/.meteor/local/build/programs/server/boot.js:297:10
W20160720-18:43:06.072(2)? (STDERR)     at Array.forEach (native)
W20160720-18:43:06.074(2)? (STDERR)     at Function._.each._.forEach (/Users/JaNe/.meteor/packages/meteor-tool/.1.3.4_3.ac04sf++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20160720-18:43:06.075(2)? (STDERR)     at /Users/JaNe/socially/.meteor/local/build/programs/server/boot.js:133:5
=> Exited with code: 8
```

**Comment by barbatus** [comment]
How do you use `Party`? You seem referencing it directly which is impossible.

**Comment by nebiljabari** [comment]
I have respect the tutorial steps. I've change a little bit the app structure to be more Angular2-ish and some pieces of code to be more concise.

If it can help I can email you my project ?

**Comment by barbatus** [comment]
To be clear, `ReferenceError: Party is not defined` is a Meteor error not a TypeScript one.
So you can put content of your `collections/parties.ts` file here

**Comment by nebiljabari** [comment]
I am not sure to fully understand your second line but if you ask me to past here my code of `collections/parties.ts` here it is :

```
import { Mongo }  from 'meteor/mongo';
import { Meteor } from 'meteor/meteor';

export const Parties = new Mongo.Collection<Party>('parties');

Parties.allow({
  insert (userId) {
    return (userId == Meteor.userId());
  },
  update (userId) {
    return (userId == Meteor.userId());
  },
  remove (userId) {
    return (userId == Meteor.userId());
  }
});
```

**Comment by barbatus** [comment]
Do you have file `collections/parties.js` explicitly? Your IDE seems compile .ts-files as well.
Do you have  the following in the tsconfig?
```
"compileOnSave": false,
"buildOnSave": false
```

**Comment by nebiljabari** [comment]
I found it ! Apologize Alex it's my fault the name of the file was `parties.js` not `parties.ts`
All works fine

**Comment by barbatus** [comment]
Good
