### ISSUE TITLE
Built bundle not running properly

### ISSUE THREAD

**Issue by paralin** [Urigo/angular2-meteor#357]
After compiling a bundle with:

```
meteor build ../output --directory
cd ../output/bundle/programs/server/
npm install
```

Running the server errors out with this:

```
/usr/src/app/programs/server/node_modules/fibers/future.js:280
                                                throw(ex);
                                                ^

Error: Cannot find module '@angular/core/src/facade/lang'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/src/app/programs/server/npm/node_modules/angular2-meteor/dist/patch.js:11:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Module.Mp.load (/usr/src/app/programs/server/npm/node_modules/meteor/babel-compiler/node_modules/reify/node/runtime.js:16:23)
    at Function.Module._load (module.js:300:12)
```

The compiled package.json looks like this:

```
{
  "name": "meteor-dev-bundle",
  "version": "0.0.0",
  "dependencies": {
    "meteor-promise": "0.7.2",
    "fibers": "1.0.13",
    "promise": "7.1.1",
    "underscore": "1.5.2",
    "source-map-support": "https://github.com/meteor/node-source-map-support/tarball/1912478769d76e5df4c365e147f25896aee6375e",
    "semver": "4.1.0"
  },
  "devDependencies": {
    "eachline": "https://github.com/meteor/node-eachline/tarball/ff89722ff94e6b6a08652bf5f44c8fffea8a21da",
    "chalk": "0.5.1"
  },
  "scripts": {
    "install": "node npm-rebuild.js"
  }
}
```

Why is the babel compiler running in the built production version? Is there something I have to change when deploying? It's not mentioned in the docs, as far as I have seen.

**Comment by barbatus** [comment]
What if you do `meteor npm install --production`?

**Comment by paralin** [comment]
@barbatus 

Result of running that then doing `node main.js`:

```
/usr/src/app/programs/server/node_modules/fibers/future.js:280
                                                throw(ex);
                                                ^

Error: Cannot find module '@angular/core/src/facade/lang'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/src/app/programs/server/npm/node_modules/angular2-meteor/dist/patch.js:11:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Module.Mp.load (/usr/src/app/programs/server/npm/node_modules/meteor/babel-compiler/node_modules/reify/node/runtime.js:16:23)
    at Function.Module._load (module.js:300:12)
```

I've verified that "node npm-rebuild.js" is indeed executed.

**Comment by barbatus** [comment]
Then I don't know. I tested on the todo demo, it works fine there. It also likely has nothing with `node npm-rebuild.js`.

**Comment by barbatus** [comment]
If you want me though to look closer, I'll need a repo.

**Comment by paralin** [comment]
I'll try to make a repro today.

**Comment by barbatus** [comment]
closing, if you still have the problem please re-open with the repo
