### ISSUE TITLE
meteor add angular2-compilers installation issue

### ISSUE THREAD

**Issue by jariwbh** [Urigo/angular2-meteor#365]
I am getting error while installing package.

E:\meteor\socially>meteor add angular2-compilers
C:\Users\administrator\AppData\Local\.meteor\packages\meteor-tool\1.4.0-1\mt-os.windows.x86_32\isopackets\ddp\npm\node_modules\meteor\promise\node_modules\meteor-promise\promise_server.js:165
      throw error;
      ^

Error: No metadata files found for isopack at: /C/Users/administrator/AppData/Local/.meteor/packages/angular2-compilers/0.6.0
    at Isopack._loadUnibuildsFromPath (C:\tools\isobuild\isopack.js:900:13)
    at C:\tools\packaging\tropohouse.js:520:19
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Users\administrator\AppData\Local\.meteor\packages\meteor-tool\1.4.0-1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:79:11)
    at C:\tools\packaging\tropohouse.js:519:11
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at Object.download (C:\tools\packaging\tropohouse.js:454:20)
    at C:\tools\packaging\tropohouse.js:598:22
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at [object Object].downloadPackagesMissingFromMap (C:\tools\packaging\tropohouse.js:595:20)
    at C:\tools\project-context.js:748:25
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at C:\tools\project-context.js:747:20
    at C:\tools\packaging\catalog\catalog.js:100:5
    at C:\tools\utils\buildmessage.js:271:13
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:264:29
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:262:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:253:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.capture (C:\tools\utils\buildmessage.js:252:19)
    at Object.catalog.runAndRetryWithRefreshIfHelpful (C:\tools\packaging\catalog\catalog.js:99:31)
    at ProjectContext._downloadMissingPackages (C:\tools\project-context.js:746:13)
    at C:\tools\project-context.js:268:9
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at ProjectContext._completeStagesThrough (C:\tools\project-context.js:258:18)
    at C:\tools\project-context.js:250:12
    at Function.run (C:\tools\tool-env\profile.js:489:12)
    at ProjectContext.prepareProjectForBuild (C:\tools\project-context.js:249:13)
    at C:\tools\cli\commands-packages.js:1976:20
    at C:\tools\utils\buildmessage.js:271:13
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:264:29
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:262:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:253:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.capture (C:\tools\utils\buildmessage.js:252:19)
    at Command.func (C:\tools\cli\commands-packages.js:1975:27)
    at C:\tools\cli\main.js:1410:23

**Comment by barbatus** [comment]
I can't reproduce. It might be an issue with the new 1.4.0.1 Meteor version itself. I had troubles upgrading to it too. Try to run `meteor update` one more time. If it doesn't help try to re-install Meteor (`sudo curl https://install.meteor.com/ | sh` for Mac, or launching installer for Windows)
