### ISSUE TITLE
angular2-compilers 0.6.3 style compiler deployment to Heroku

### ISSUE THREAD

**Issue by bergben** [Urigo/angular2-meteor#427]
**I'm submitting a ...**
```
[ X ] bug report
[ ] feature request
[ ] support request
```

**Current behavior**

When deploying to Heroku the styles seem to create an issue at compilation (style_compiler.js): 
```
remote: Errors prevented bundling:
remote: While processing files with angular2-compilers (for target web.browser):
remote: /tools/isobuild/compiler-plugin.js:698:15: 'data' option to addAsset must be a
remote: Buffer or String.
remote: at ResourceSlot.addAsset (/tools/isobuild/compiler-plugin.js:698:15)
remote: at InputFile.addAsset (/tools/isobuild/compiler-plugin.js:463:24)
remote: at SassCompilerExtended.addCompileResult
remote: (packages/barbatus:css-compiler/compilers/basic_compiler.js:32:15)
remote: at packages/caching-compiler/multi-file-caching-compiler.js:144:14
remote: at packages/caching-compiler/multi-file-caching-compiler.js:97:11
remote: at
remote: /app/tmp/cache/1.4.1.1/.meteor/packages/angular2-compilers/.0.6.3.1o2aiwn++os+web.browser+web.cordova/plugin.Angular2Compilers.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:182:20
remote: at replenish
remote: (/app/tmp/cache/1.4.1.1/.meteor/packages/angular2-compilers/.0.6.3.1o2aiwn++os+web.browser+web.cordova/plugin.Angular2Compilers.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:317:21)
remote: at
remote: /app/tmp/cache/1.4.1.1/.meteor/packages/angular2-compilers/.0.6.3.1o2aiwn++os+web.browser+web.cordova/plugin.Angular2Compilers.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:324:29
remote: at
remote: /app/tmp/cache/1.4.1.1/.meteor/packages/angular2-compilers/.0.6.3.1o2aiwn++os+web.browser+web.cordova/plugin.Angular2Compilers.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:44:16
remote: at packages/caching-compiler/multi-file-caching-compiler.js:148:9
remote: at
remote: /app/tmp/cache/1.4.1.1/.meteor/packages/angular2-compilers/.0.6.3.1o2aiwn++os+web.browser+web.cordova/plugin.Angular2Compilers.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:182:20
remote: at replenish
remote: (/app/tmp/cache/1.4.1.1/.meteor/packages/angular2-compilers/.0.6.3.1o2aiwn++os+web.browser+web.cordova/plugin.Angular2Compilers.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:317:21)
remote: at
remote: /app/tmp/cache/1.4.1.1/.meteor/packages/angular2-compilers/.0.6.3.1o2aiwn++os+web.browser+web.cordova/plugin.Angular2Compilers.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:324:29
remote: at
remote: /app/tmp/cache/1.4.1.1/.meteor/packages/angular2-compilers/.0.6.3.1o2aiwn++os+web.browser+web.cordova/plugin.Angular2Compilers.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:44:16
remote: at packages/caching-compiler/multi-file-caching-compiler.js:148:9
remote: at
remote: /app/tmp/cache/1.4.1.1/.meteor/packages/angular2-compilers/.0.6.3.1o2aiwn++os+web.browser+web.cordova/plugin.Angular2Compilers.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:182:20
remote: at replenish
remote: (/app/tmp/cache/1.4.1.1/.meteor/packages/angular2-compilers/.0.6.3.1o2aiwn++os+web.browser+web.cordova/plugin.Angular2Compilers.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:317:21)
remote: at
remote: /app/tmp/cache/1.4.1.1/.meteor/packages/angular2-compilers/.0.6.3.1o2aiwn++os+web.browser+web.cordova/plugin.Angular2Compilers.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:328:15
remote: at Object.async.forEachLimit.async.eachLimit
remote: (/app/tmp/cache/1.4.1.1/.meteor/packages/angular2-compilers/.0.6.3.1o2aiwn++os+web.browser+web.cordova/plugin.Angular2Compilers.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:221:35)
remote: at SassCompilerExtended.processFilesForTarget
remote: (packages/caching-compiler/multi-file-caching-compiler.js:95:11)
remote: at _loop (packages/barbatus:css-compiler/compilers/style_compiler.js:20:26)
remote: at StyleCompiler.processFilesForTarget
remote: (packages/barbatus:css-compiler/compilers/style_compiler.js:18:36)
```
**It works fine when building locally.**

**Expected behavior**

Deployment to Heroku is possible.

**Minimal reproduction of the problem with instructions**

*STEPS TO REPRODUCE*
- create angular2-meteor app using https://github.com/bsliran/angular2-meteor-base
- Add styles as mentioned in the css-compiler readme: https://github.com/Urigo/angular2-meteor/tree/master/atmosphere-packages/css-compiler
- Follow instructions: https://github.com/AdmitHub/meteor-buildpack-horse to deploy to Heroku. 

**Current alternative**
Would be to use fourseven:scss and angular2-compilers@0.6.0 I suppose.

I think this should be a minor issue @barbatus. Maybe I am just missing something. If I can help in any way please let me know.

**Comment by derek-fong** [comment]
+1 

I am having the same issue when deploying my app to Ubuntu/Debian Linux with Meteor Up. 

Works fine when using `angular2-compilers@=0.6.1`.

**Comment by bergben** [comment]
but then you can't use angular 2 final, @derek-fong right? There was another issue with angular2-compilers and angular2 final before version 0.6.3...

**Comment by metalik** [comment]
Got the same error when build at local machine as well:

```
Errors prevented bundling:
While processing files with angular2-compilers (for target web.browser):
C:\tools\isobuild\compiler-plugin.js:698:15: 'data' option to addAsset
must be a Buffer or String.
at ResourceSlot.addAsset (C:\tools\isobuild\compiler-plugin.js:698:15)
at InputFile.addAsset (C:\tools\isobuild\compiler-plugin.js:463:24)
at SassCompilerExtended.addCompileResult
(packages/barbatus:css-compiler/compilers/basic_compiler.js:32:15)
at packages/caching-compiler/multi-file-caching-compiler.js:144:14
at packages/caching-compiler/multi-file-caching-compiler.js:97:11
at C:\Users\XXX\AppData\Local\.meteor\packages\angular2-compilers\0.6.3\plugin.Angular2Compilers.os\npm\node_modules\meteor\caching-compiler\node_modules\async\lib\async.js:182:20
at replenish (C:\Users\XXX\AppData\Local\.meteor\packages\angular2-compilers\0.6.3\plugin.Angular2Compilers.os\npm\node_modules\meteor\caching-compiler\node_modules\async\lib\async.js:317:21)
at C:\Users\XXX\AppData\Local\.meteor\packages\angular2-compilers\0.6.3\plugin.Angular2Compilers.os\npm\node_modules\meteor\caching-compiler\node_modules\async\lib\async.js:328:15
at Object.async.forEachLimit.async.eachLimit (C:\Users\XXX\AppData\Local\.meteor\packages\angular2-compilers\0.6.3\plugin.Angular2Compilers.os\npm\node_modules\meteor\caching-compiler\node_modules\async\lib\async.js:221:35)
at SassCompilerExtended.processFilesForTarget
(packages/caching-compiler/multi-file-caching-compiler.js:95:11)
at _loop
(packages/barbatus:css-compiler/compilers/style_compiler.js:20:26)
at StyleCompiler.processFilesForTarget
(packages/barbatus:css-compiler/compilers/style_compiler.js:18:36)
```

**Comment by derek-fong** [comment]
@bergben yes you are right but I have no choice but rollback to `angular2-compilers@=0.6.1` until is issues is resolved. 

**Update**: `angular2-compilers@=0.6.1` works with `@angular 2.1.0` on Mac and Linux but deployment still fails with the same error mentioned if using `angular2-compilers 0.6.3`. Here is my `package.json`

```
  "dependencies": {
    "@angular/common": "2.1.0",
    "@angular/compiler": "2.1.0",
    "@angular/core": "2.1.0",
    "@angular/forms": "2.1.0",
    "@angular/platform-browser": "2.1.0",
    "@angular/platform-browser-dynamic": "2.1.0",
    "@angular/router": "3.1.0",
    "angular2-meteor": "0.7.0",
    "angular2-meteor-polyfills": "0.1.1",
    "angular2-moment": "1.0.0-beta.5",
    "babyparse": "0.4.6",
    "es6-shim": "0.35.1",
    "meteor-node-stubs": "0.2.3",
    "meteor-rxjs": "0.3.0",
    "reflect-metadata": "0.1.8",
    "rxjs": "5.0.0-beta.12",
    "zone.js": "0.6.25"
  }
```

**Comment by bergben** [comment]
Should I reopen this issue in the current moved repo? Seems like this repo is not actively followed anymore?

**Comment by barbatus** [comment]
@bergben does it work fine if you run `meteor run --production` or the same?
(Sorry for long delay)

**Comment by omararturo** [comment]
Hi,
In found a solution that worked in my case:

My application worked perfectly in local mode.
But when he tried to make deploy appeared the following error:

```
Errors prevented bundling: 
While processing files with angular2-compilers (for target web.browser):
C:\tools\isobuild\compiler-plugin.js:698:15: 'data' option to addAsset must be a Buffer or String.
```

An error that really does not identify the cause, hopefully in the future we @barbatus provide some help.

When removing my application modules and keep trying one by one the modules arrive at the cause of the problem. In one of the modules he was importing a CSS style sheet that was empty

```
import template from './create.component.html';
import style from './create.component.scss';

@Component({
    selector: 'create',
    template,
    styles: [style]
})
```

The file "create.component.scss" existed but had not yet enwedged any code.

When I deleted the empty file "create.component.scss" and remove its relations with the component or add styles to file the problem was solved. I could perform perfectly deploy.

I hope it will be helpful to you.

**Comment by bergben** [comment]
No worries @barbatus, I know you guys got a lot on your minds, just keep up the great work 👍 
The problem also exists using meteor run --production. 

Thank you very much for posting your findings here @omararturo. I can confirm this. After adding a css rule in every single style sheet used, the deployment works like a charm. 

So to reproduce this issue you simply have to add a completely empty stylesheet to a component and run meteor in production mode. 

I suppose this is only an issue during deployment on a server as I am deploying constantly to Heroku during deployment. So it's not that big of a deal for most use cases.
